### PR TITLE
Distribute only for: win64, linux64 and Macos intel 64

### PR DESCRIPTION
**Pull request by alessio-perugini**
We depend on 3-party tools that are not always distributed for every platform, therefore we have to match the same platforms.

### CODE REVIEW

**Comment by cmaglie** [comment]
Why?

**Comment by alessio-perugini** [comment]
@cmaglie all the tools used by this plugin (especially esptool@3.3.3) are released only for 64bit arch. So the minimum common ground is 64bit.
It doesn't make sense to compile the plugin itself for all architecture if at the end of the day what makes this working is the interaction of external tools like esptool

**Comment by cmaglie** [comment]
> It doesn't make sense to compile the plugin itself for all architecture if at the end of the day what makes this working is the interaction of external tools like esptool

Who cares :-) it will be the fwuploader to block the user from the installation because a dependent tool is missing but, eventually, if a build of `esptool` for another OS becomes available we will not have to touch here again.

**Comment by alessio-perugini** [comment]
@cmaglie If a new version of  `esptool` comes out, we will have to bump the pinned version in the codebase and create a new release of the plugin. I see your point that we don't have to modify every time the CI stuff.

My POV is that the plugin is fully functional only when it can invoke the tools:
- It doesn't make sense to release the plugin on the architecture where the pinned tools were never available because it doesn't benefit our testing.
- Users expect that we fully support that architecture, and we cannot guarantee that.

We can always bring this up with the whole team and see other opinions too :nerd_face:

**Pull request merged**
